---
title: "The beginning"
description: |
  Trying to put the phrase "Done is better than perfect" to practice
author:
  - name: Jolene
date: 09-04-2021
output:
  distill::distill_article:
    self_contained: false
---

At this point, this blog has been in the works for close to half a year. I struggled a lot with what to post on this blog and I still don't have an answer. Every once in a while, inspiration hits and I draft up a half-baked post but I never actually published any of them. I have loads of incomplete drafts and one-liner ideas stashed in a notes app. I know I just need to take a stab at them. I recently watched the movie *Tick, Tick, ... Boom* and the line *"maybe try writing about what you know"* seems extremely relevant here. Since I have been working on a couple of small projects, I think I will start from there. There's going to be some embarrassingly basic posts here. Some posts will simply be yet another variation of *"how I managed to do xyz"* on the internet. Who knows? My perspective might provide some value to a lost and confused soul who found their way here through a right combination of words in the search bar and Google's invisible hand.

I wish I could say <a href = "https://rstudio.github.io/distill/">`distill`</a> `r emo::ji('package')` is simple and straightforward. Well, it was at the start. I had it set up pretty quickly, then promptly left it to rot for months. When I finally decided to actually launch it and publish posts, I ran into a slew of problems. It's definitely more straightforward than `blogdown` `r emo::ji('package')` though. For now, I'm still tweaking the css and thinking of a domain name to buy. Sinking some money into this will hopefully motivate me to update this blog regularly.

### What's next?

Random R tips/guides. Curation of interesting R projects. Data explorations. TidyTuesdays. That's a wish list. Realistically, this blog will not have consistent updates. My only hope is that I will keep this running, regardless of the pace.

Here goes nothing!
